# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# include ActionView::Helpers::AssetUrlHelper

cap = User.create(fname: 'Steve', lname: 'Rogers', email: 'captain.america@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/captain-america.png')
cyc = User.create(fname: 'Scott', lname: 'Summers', email: 'cyclops@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/cyclops.png')
dare = User.create(fname: 'Matt', lname: 'Murlock', email: 'daredevil@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/daredevil.jpeg')
dp = User.create(fname: 'Wade', lname: 'Wilson', email: 'deadpool@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/deadpool.png')
drs = User.create(fname: 'Stephen', lname: 'Strange', email: 'doctorstrange@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/dr-strange.png')
gambit = User.create(fname: 'Remy', lname: 'LeBeau', email: 'gambit@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/gambit.png')
hulk = User.create(fname: 'Bruce', lname: 'Banner', email: 'hulk@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/hulk.png')
im = User.create(fname: 'Tony', lname: 'Stark', email: 'ironman@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/iron-man.png')
prof = User.create(fname: 'Charles', lname: 'Xavier', email: 'professorx@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/professor-x.jpeg')
psy = User.create(fname: 'Betsy', lname: 'Braddock', email: 'psylocke@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/psylocke.jpeg')
rog = User.create(fname: 'Anna', lname: 'Marie', email: 'rogue@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/rogue.gif')
sm = User.create(fname: 'Peter', lname: 'Parker', email: 'spiderman@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/spider-man.png')
storm = User.create(fname: 'Ororo', lname: 'Munroe', email: 'storm@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/storm.jpeg')
thor = User.create(fname: 'Thor', lname: 'Odinson', email: 'thor@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/thor.jpeg')
wolv = User.create(fname: 'James', lname: 'Howlett', email: 'wolverine@gmail.com',
  birthday: '2000/1/1', password: 'hunter12', img_url: 'https://s3-us-west-1.amazonaws.com/mymaprun-pro/users/images/wolverine.jpeg')

f1 = Friendship.create(requestor_id: cap.id, requestee_id: hulk.id, confirmed: true)
f2 = Friendship.create(requestor_id: cap.id, requestee_id: sm.id, confirmed: true)
f3 = Friendship.create(requestor_id: cap.id, requestee_id: thor.id, confirmed: true)
f4 = Friendship.create(requestor_id: cap.id, requestee_id: im.id, confirmed: true)
f5 = Friendship.create(requestor_id: cap.id, requestee_id: drs.id, confirmed: true)
f6 = Friendship.create(requestor_id: cap.id, requestee_id: cyc.id, confirmed: false)
f7 = Friendship.create(requestor_id: cap.id, requestee_id: wolv.id, confirmed: false)
f8 = Friendship.create(requestor_id: cap.id, requestee_id: storm.id, confirmed: false)
f9 = Friendship.create(requestor_id: cap.id, requestee_id: psy.id, confirmed: false)
f10 = Friendship.create(requestor_id: prof.id, requestee_id: cap.id, confirmed: false)
f11 = Friendship.create(requestor_id: dare.id, requestee_id: cap.id, confirmed: false)
f12 = Friendship.create(requestor_id: rog.id, requestee_id: cap.id, confirmed: false)


r1 = Route.create!({name: "Escape from App Academy", description: "", creator_id: cap.id, distance: 6.54, polyline: "urueFdnajVnAOIiAq@kKG}@G_@So@a@{@O[KUlC_CbByAdFqEvDmDhHsGnAsAvAuAbBoBdKwMj@a@pEoBz@e@h@i@POj@Yj@SlB]hAQ`AG|@AhADlTz@`FTtCFh@GRI`@[XKrKe@bDK|E`QLVPSbBoAZGfCOx@EbDUvDUdGSlG[tTaAfCSlAGrAAv@AjCO~FWvCIlHKv@IvGY`DMzEUbDWhHe@~Lc@rBOn@E~AGlFKdI[zH]dEQj@GvAEpCKj@@bANxD`AbATlDz@`JiRzDqI|HgPDYxBsEn@iAjBiE`@u@VWhD}Ar@Un@CzALvAJjBVr@RPMJAtA?JCXKTOb@i@jB_EnG_NfGqMzA_Dw@s@yDmDlGyMCu@NuILsFzGzFf@IVD^B`Ba@", waypoints: "qrueFloajVvv@{nAnaHmEvkBqnC", bounds: "{\"south\":37.726168,\"west\":-122.40135312080383,\"north\":37.798967375853046,\"east\":-122.36457200000001}", city: "San Francisco, CA"})
r2 = Route.create!({name: "SF to NY", description: "", creator_id: cap.id, distance: 2913.7, polyline: "exqeFjccjVkzHcr^uLq~FbgAqaKqeXeeZezKm|KxIgdNrH_~IcaEqrImnKe`IueAmvJlQ{|^ykC{rs@uzJgdZahTa~PorLwr`@qqJarJacKaac@_gEipZo_Oere@muF}iPq`JsqOrFkrPuoLirLhg@miIyhSy|Isrd@|CwrQskIeik@ynrAg~Kg`i@olHis`@jbDmwSmdAmeh@ubI_hTe|B}xNwpLopHjaAefSovG}yOeda@gj[qeZ}a_@em_@yvx@anT_hRq|q@{xjAexVkgZj|BwgF{kCwfWqjLaoo@{eJybVctDuxQi{BwoHvmK}mf@o}Sej}@_{Z_~m@ykKgci@gsLwrdBwrV}_e@qZs}b@cLmrMehMupi@kuO_bc@glGmv[{bLcaJaiNsoV_aKs|cA{oOkwj@`{E{mh@`hC_bSvkJoiVzQkdP~pB{{UkfGuiLiaIsgWkrDakPscD{dMx~DizYsdA_zXkzBexMavFi`a@qpD}_SnpBafUfaGuzQgiFesh@iYw|`AigIwgWq|Qsu}@raAcws@bjAyv^q_Mwu]uad@_}dA{nY_{~@_mBil]wgNo}Vq{Fkv`@c~I{}d@|bEmwlA`nB_~hAwlHkeLchKox[ngCm`Ghh@gwl@kkLkwRsvLw}c@ibHmgKohBgqUupFunTs|GqhUoj@khmAnRowb@oy@myRhtFsxYd`LsrPib@kzb@|kAooj@skCqyz@tsEspz@v`Ows|@soCu`cAjkBqrc@scG}r^ooVs|aApiJmne@fnNozR_fAwlXkxQed_A{c@it|@wxNwhPqtEqajAgm@o|iCjiWazu@jmJmyNvk`@wgx@rgDa|k@ysCuxt@yqFivpAnfW_yx@|sBgmxAqEkcaCiDi}rDjxByjw@klFiuc@zTqsyAlmE_azF{t@{zwC|ByyvAny@ojg@h`GcqR~bBszu@dxKqea@~sCcdkBppR{zj@~pZ}_e@z~Y}zo@fzSc{eE}vCe{~@||M{bfAhsCshuA~mEad_@~_I{jqAlxJcudBdfDe}gBrvMgrjB~gEg~fDn}E_zsDcOacqDzgGyok@xqAa`v@|~DeboA|_LegqBdhDymqAfjAavmDwKmo|BtjAoiaCwj@k}q@gnIsv]h}F{udAlsOagfAf|Ly`u@loAgmd@pcIsld@xeOisz@xt@{x~@~qQijVkcLe{r@iSuqy@cqLswhAqrMm{_BdrE_nmAvrB}|s@h{W_im@jaGshk@_lDmuj@d~DosV~{Eaa|@xpHg~aAjyBu`Q", waypoints: "gxqeFlccjV_d~PctnfH", bounds: "{\"south\":37.779398571318765,\"west\":-122.40966796875,\"north\":40.7241976,\"east\":-73.9966905}", city: "San Francisco, CA"})
r3 = Route.create!({name: "Cuban Dream", description: "[CLASSIFIED]", creator_id: cap.id, distance: 532.92, polyline: "sw`lCh}wuNxjCyuDpr@u|CtyEw_IdrEkeHniCmhFfaBulB`fAqoBtBmeAh}BanDjXwoBoM{t@~O}yC`WmjCt^moHqu@_n@yyFosT}i@{aHyp@c{Cvt@ofMu}AgeDiaA_cEm~@{pDae@}}BnDg`Chq@u@vyCkhGdAq{FjuA_z@jzBkgEpm@{rDqKwhD_b@k|AfyByuD~|BmvI|iAkvBzxD{_DfkFgvD~zE_mH``AioSvWecDrXwwBv_D{`NhqBi_Fhm@ybBn_AyGlh@k}@z~As}EfBkkCtC{`B{aBohI{lA{xEmg@c{C|pCoiNxfCokKt|Ign[|zC}vNtkDazKx_BwlGbL}v@lsBiR|sBu^vp@xRf}@kvAdXa[fdAbz@n}@ccAxj@ckAvJ_hBqDkZyRsq@}Bua@no@evCbt@_fC~{Be_EnuAaaEh|A}lA~DebBwJukE|k@_eDh_@}oCke@coEnmAcjGdfAenClbBkqFx|@sbDjSodEnaCsmDd`B}vDvlAydGriMivFxzFe}G`uDwsBhqEmxBn}C}^v`Ce}Ahi@{qArzC}oCj\\ke@zoBvGloErI|vC__A|iCuaAlxByzAgSqhEbpBwaD{lCysUirBaiLzgBwuBc|@qfBvGooGdmA{hOjzH}uXxu@emCzb@epE~{BofIniAuwDiIoaBxgBwgJniHy{QflTqjh@pwGoaQdcFobFhbBofAh_BhYz}BUrv@ooAftFkoFheJibJfvCcmEbPedEqPuvGn|A{_DkKkl@w@_wClT}xCxtBqlEnPwlArcDsiDdq@mxApeCevBlyBwz@ltAe`CsKsgBjVebElTwwDnjA{wIdkAicGz_E{uFpAofC{m@eyAkjAghCnWqaAf}CuhEnSyuCv`F}vAzsB{FfhBqfB|aCivBvsD_dFjfDgaC}HwxNaMmwAdfAk|C~bAexCwJg{BruAeoH}VgyK`gM_yT~oC_nGraAayCvMqnBHktH`a@uyFdm@g}AjxAmwDjV}nCjGsiEpMm}AdcBqeBv|@cjEt|@wvDwBwiDeaAoyEhWqoFwa@_wGsf@wmAme@ibOiSkeIdeAooDuIuvFmP_cAtAur@gAhj@zCpt@hXlcAdJv_C|Z`dAd~@|h@bjCb^v|QlrHj}BpoC||@dbAnnBKhvHmh@n|Asf@biDeNdc@icCpv@ehDZq_CflB_aCrrF_|InwCjgBiMt^d}Aez@tz@_yBv}BajB`qBmbBpq@_yAfnBidApu@bVpoAuJdb@ve@znAnyB~mE|Gf`@sV", waypoints: "yt`lCx}wuNpepFqykT`kcEm}eOlshBqlH", bounds: "{\"south\":20.3287572,\"west\":-82.37548828125,\"north\":23.11004929735674,\"east\":-76.1638792}", city: "La Habana, La Habana"})
r4 = Route.create!({name: "Golden Gate Park 6mi", description: "", creator_id: cap.id, distance: 6.64, polyline: "g_peFdwvjV`A{Cd@aAjAkBh@k@xBiB|AeA|@g@zBgAb@YZa@\\e@MaAwC{Sk@{CSeAi@_CODmAkEYiAY_BUgBGm@J@I]_@uCy@eHG{AOq@Mg@[q@y@{A[w@W]YiAg@wB[cB_@}CQsB?uBFqALoALgBBqACcBMeBGcAB_ADe@b@{At@gB`AgCL{@CcAa@gCEcABw@Fq@TmBDcBAu@GaAQiAy@sDuAkFuAyESgA[cCWkCEeA@wAH{@j@{Bn@uB~@_EVyAD_AEe@Kk@YaAg@gA_BuCaBoCUg@[{@Q{@Gi@IqBEuFIgC?eAFmAPgB`@cCv@kEp@aENyAr@mIRqBDs@ZSL[h@r@RVKZNHHFLN^v@RbADn@BnA?nABbAJjAv@lFt@bFNr@\\~@j@~@hBjCt@vAhAvBJLIPw@bBWj@sA|CSt@WpAOtAG|ADvCJjANv@^`AT`@XXh@\\XHf@FtAR`@L`@\\NPVb@JVRx@xA~Hl@lDh@~DFpAHhBPrADXOFEBEN@\\Gj@}@jCa@rAa@dBOdAIbAGvBBzADdA`@rCBt@Cx@SzBc@fAK`@Gx@@j@Dn@LbAH\\Pb@bA~Bl@jA^v@b@bAP~@Lv@LvAXtDDrBEtAF^CBEJAF@GDKBCB\\GfGI|ANBrBHT?@NJrGBrDRrJTlNt@bf@VhQ@xB@vAQ@O@QA{@OsAGeGHkFVO@@VBVM@yDf@sARaDV", waypoints: "m_peF`wvjVzGkgAsFiaB}D_tCxPxo@hL~jAfB`mAtEnt@L|~@y`@tC", bounds: "{\"south\":37.76442,\"west\":-122.51094089999998,\"north\":37.7710586,\"east\":-122.45894049999998}", city: "San Francisco, CA"})
r5 = Route.create!({name: "Hong Kong!", description: "", creator_id: cap.id, distance: 6.21, polyline: "{obgCadzwTBNBBZNTHn@CBHB^@DF@d@ADA@tA?JB@B?D@DDDH?D?@^@T?@|@~@A^ENEJIPA|@?FbD?hBH?HE|@?JNBPREv@KdAQ|Ca@zBWl@In@Id@GDDBBH?\\IFXDh@zAdAf@t@bAxA|RjVhMpO\\XdAt@fC`A^PGVERI^?H?D@@JYDIFCH@@D?JBJPTH@J?ROnAd@dAp@gAnCfAoCdBeDTk@T]TUDAHIDK?E?CVFhAXh@ALGNOP]Vy@hAeE`AkEJo@VwCDi@MCGILoBTYE[Ee@AKB@D{A@UBKBAJ@@_@Hq@Rw@`@gAP]d@c@ZMTCp@?rAN@aAMcIH_@\\kARaDHkAYiJImCAOd@AdCMXSFi@?a@g@}GEE]yBBEEOlAaAJKb@M@@@D@DDCpBe@jAYcA{FIe@XI~Bq@~@Wn@SCKYeB?yAGe@p@AXGLIs@@S?Mi@[wAc@qA_@NBJADEJC?UIEAD@THB?DK@ECK^Ob@pAZvALh@GAwBIw@EK??ZCb@wBGw@FcAZ`AbDX`AAh@MB}@XYHi@TkDfAsC`A]Nq@RkAX`A`EHj@Z~CQEQKKIKAe@@qAJk@JeCRiBj@gC~Ay@l@k@l@eAjAcAxAoB`DwMdYoApBWXmAz@u@\\wBd@kAPiAHu@?_CQiA]c@UgCgBg@u@{AeAEi@YuAWwCQ{DAg@GcBAe@G_CGg@G}@Y}Bg@}BK]Ue@MW_AKaHk@aDc@cD]aC[_C]iBc@", waypoints: "iobgCgdzwTlyAvlA|l@wmCojCxb@", bounds: "{\"south\":22.278389051701627,\"west\":114.15927769533687,\"north\":22.3007069,\"east\":114.18211609907235}", city: "undefined, Kowloon"})
r6 = Route.create!({name: "San Quentin out-and-back", description: "", creator_id: cap.id, distance: 33.83, polyline: "wfveFdqnjVh@lDcGCcCv@eA|AyAj@yAW}Bb@aBjFcEjIiCjFg@fCRlBXXKRi@z@BtBsC~AmHd@q}@xEoh@rDmGf@gHVgHbAqE|DiBhA}@e@@|BBtAiCfFwDlC{DUG?EDc@^[o@KSQUwBmA{DEeESaDmDg@mEHmK}@cDuBiByBSgHbCsGk@qD]iAJaErAyAdB]vJqP?S{DkBo@iEyBcJCcIBwHzDyIpMyGhU{J`YaApGUtOeCpHkHvMg]x]oIjD{Cz@qDbEcF`KiYja@aJzMeSxXoX`_@qErBgm@`G}Hb@wUdCg@WeEqI}IiGmAcD[oETgKLiALy@Yq@uGoBcAiC}AgA}DsCyC}@^iFuJeEmQiFsD@uPeFwH{@oH\\oNfFyO|Gy@jAw@pTI`CqV?oGsCkGCcHf@{K|AeBcJ}AuEqCrAkDCyCk@gLmAiHqAoK_CmBk@[uApAMaBSkH_A}EkCiNwGsUuT_Cw@qEEwK~CsBrCNjAuAlCuH`IaD`CeAhGuB~BkHxNOhB}Ei@aAXuAbCkEzHeEtI}B|AaHq@eInJWLIo@TqFd@oDx@XbBaA~AwA`DkEfKaS~Sad@pF}MjD}Kx@{D[}AiBeJEeDv@?~Cd@jE_ApK_KhB`Dt@Gb@?dAc@z@AvHiIrW}XzOwPhKqST_AGZeAtCkHjNiJlKwl@`o@gPrOuDzAoBfBRjA|AbCjCrDvBfDxDvGzCsC~DuA|F{@fE^rAp@lQ~P~HpExLxG|FzAvE@GZwAAtA|BvLxC^K`Cb@xMbBzIxA|FmBpCnKn@pDGr@h@dL`ASrG[~GxAZB`FhDpAb@l@IbVJRIlA\\dJX`JBnCM^@pAnBfEo@PCx@b@lAq@^uCjAaE|BmD~ALtCdAvCm@rDOLr@p@t@~AbAB`AkB~Ec@hEj@|D~A`ApDs@vLjDx@XF{ADe@fGhBzCj@bE^fQtAlLdDlHm@~@ErSeBlBg@f]mCzZoDrDcCp`@kj@bHgJr@oAt]_g@tIqNrBgEjE}DlEeAhBu@~IqGbRcS`HcJnGqOPqIp@gLlCiIbL}[~AkHnGaLpAmBhHqD|TWnHdDf@l@@HAjC~DB`GBzA@TON_ER}DzAaBfHyA~HvA~IgC|BAxBjAjAbCTvQpBjEnDjAzFG`D`Bn@lAj@g@vB`@zDkAbEyGAqCXwAd@`@x@o@fAg@`BiBzF{BdO{@xH_@lzAgJhNg@~DsA~@aAWuAZq@VUQa@[uA|AiHQuB`D{FfAe@`CyF`C{@nBXzAo@zAmBdHm@|@]WmA@e@", waypoints: "ajveFdpnjVuyZp{B~|ZqzB", bounds: "{\"south\":37.8021998,\"west\":-122.48796170000003,\"north\":37.9452439,\"east\":-122.46803283691406}", city: "San Francisco, CA"})
r7 = Route.create!({name: "Manhattan Loop", description: "", creator_id: sm.id, distance: 8.9, polyline: "anpwFvvubMoHq@kAOSAGECCuCW{BSaCWwCSiGm@yHs@wMkAoBS}BKcGe@]IyFg@eCUYGSKe@a@IOOVGFIJKBK?gAOsJy@{BOaDa@oAM[I}@k@cAk@[G{A_AgD_CsBqAyDiCqH}EcCeByBuA_CwAaAq@{@i@sFqDqFqDmCkBkBsAUI_DyBsAy@{B_Bi@_@uCkBMAg@_@_@hAOd@{@fCs@|Br@}BdFwOtB{G{ByAwFsDiK_HsNkJsNmJ{FsD{B}AcJ}FsA}@MUAY@e@AMGMS[KIRo@EC\\eAtCmJpEgN^qANH~BzAhO|JrL|HzFtDfYbRTYXIJETPlBnAJFH]Xw@TNJ_@h@cBh@\\vCgJtFpDvFvD`GxD~FxDlNfJvJnGfAp@XRBELIPAjAN|@P^NjCj@jARfAVdC\\hAPlB\\`@JRFrCb@XNRJ~AdA~BzAJWZHXHR@l@AVGNWNc@@MBAVm@\\gATw@RAxAK`@?x@BXDHCXDbNtB\\Cv@LhBZnBl@|Bl@N?V[Zq@jBnAb@X`@NvA\\|GdBfCn@jCp@ZBjFzAJBRmA[MMMEMAW@MAL@VDLLLZLSlALDnAZUv@y@hCcAjDy@lCILuArEk@`Ba@vAoA~CuCpHoA|CpFhErFlEFF[dD_@jDGh@KpBG|BG`AGj@QnDDBLFZFRAFAJR?JDTNZNBhFd@dAJ", waypoints: "_npwFfvubMmyE_iA{x@iyB~qAre@|xDzx@hFhcB", bounds: "{\"south\":40.72176227543699,\"west\":-74.00827549999997,\"north\":40.7659677,\"east\":-73.9767941}", city: "New York, NY"})
r8 = Route.create!({name: "Yellowstone Nat'l Park", description: "", creator_id: im.id, distance: 115.59, polyline: "mlknGpflcTlDlPrFnA_CtMsKnT{FbY_M`Lwm@|]i]~a@qU~EiWeEaq@ys@ck@mc@ap@{EmW{ImAj@qFv@oXbDuUth@cc@vH{q@_@mh@nY_bAwf@wNhEsaAch@oOyH}[cBcLyQcWjHcq@g@s}@fOsYnt@ks@|hA_aAta@{b@gM_SmKkKxTyRgEsUzW_RgKmNcTqRew@jEy\\iIqbAaTszAtSelBxFiW{AcbAv@kx@kOqVqSBmPgLgK}SxBo[bJc[aNi]dQgUb@{RaN{Eur@zA_UmK{\\bVgn@iIs`@~@wVnIe^{Osh@bH}g@i`@i^qlAyK_}@xGg_@aIy^ea@q~@qNkBwGtCxCpBbHhFm@hFoElQqDk@aHBpJd@lHmV}KeN|D_j@eBc]lk@}mBlDahA}Bso@}AeU`Mk[pR{x@fy@usBjJwlDwNohA}Twi@_l@g{AwRyoB_\\y{@}l@uDuNwOeCgcBaEga@Zu^|Z~@xo@nBfLlJ~G~f@vMzMbk@pBfYuJtWnMdRuG~U{Uho@uThTgItk@c}@jq@oyAda@ee@lb@cIva@vDfgAev@p~@ceA~F{i@rUa[re@{i@fZwdAbSgNlKso@vI_gAnHus@fNcEfw@`WzdAs[`WgNhUaEvJxJjl@de@vIyg@tm@c_DbBmvB}IcrA`i@ikBpo@}pAfXcTnYdOtM|Qr_@fLnHwM{EoUt[}u@zy@gd@rd@~Lso@wLez@ds@cPp^tCjVkJjUce@}LsHo[{\\qAci@bs@uk@r~AeTvgAfJhqAl@|wAoYp{Aq_@beB_B`\\d_Ad{@xIfk@vXzUfNvb@bEfQbOrCdTrNtNjg@p[th@d\\xNxa@tmBvHv`AfPdc@jNpc@fM~Uz@vu@d@bXpHtInGby@voAbbByDrh@tVrOxQbBbXlIj\\~j@za@fc@|OpEpEbQhErRtOxRvh@jFfg@nLd_@~`@dOfE~VwExWzZvPzg@jYlp@jc@xSrNiPnCcZdZaRl_@qExTtYvRkNzXk^nVqIdv@|HfaAtTna@xPol@oRiuB_\\kr@zq@ki@lv@yUjEcAhU`KbHnRAtHnWyiAftDi^riARxu@tBvr@vMdKmBrQpGpa@i@zg@_XtZog@nAoWhLiX`HKtSuQpOh@jVrQ`TvH~e@gFjp@tCfc@|Q~GnThd@lWpg@eEn_@bT|WvC|x@|S~g@kBzhA`Fj[mKdl@kLr{AeUrx@{u@zg@em@ls@uAp^xLzZ_Mle@aDhMq@bHkEk@l@mHe@eC_GoPoDoNmDlEwMtAwDiCeKkFj@eI", waypoints: "m~knGnthcTicr@mzRbcj@ybrAdnXbly@_|Odco@", bounds: "{\"south\":44.3776704,\"west\":-110.82360799999998,\"north\":44.7289231,\"east\":-110.27812180000001}", city: "Yellowstone National Park, WY"})
r9 = Route.create!({name: "Peaceful. Nature.", description: "", creator_id: hulk.id, distance: 232.25, polyline: "wggeF`}eyUmHqlAf@cbA}cAep@sn@}iA{Lgi@hNa^`AoyBtGcr@g\\of@}]yNqi@ym@yNcKkJzIm]|PaQmPug@wa@}a@jB_Nm_@mTmKeAmm@eSgeAih@}Fyv@oc@iHwv@dCeu@q_@m]kaAqx@}XkMiVit@slAoqAq|@sl@}{@_k@kj@o^kKql@_LgVBgy@i[_l@fl@{gA~SafBnL}rAaJmrArParAzYujDjbAgw@vh@_l@ld@uKjsBiv@bv@qg@lkBki@fjAh@jpAif@tj@xKuNug@|_@cm@eUu_@rMwv@xnAieAjVgk@va@k~Atj@s_AxLivAxEu[gJkNiB_Y|F{YP}e@xG_cAfu@yuAzmAahB|e@o]vbAsnAz\\__A`DRpNpItr@{oAlp@iVdo@{Kv]{WhJk}@~EahAoU_cAb^iuA_Km_AjBej@__@uF`NaeA~VaJtImzAxm@y{DcOsdDzF}u@n`@o`B`k@wbDr`Bo_IzqC}fCl`BirG_B}dDpOmtBbaAmsCzTcaCdq@}xAbdAmAfy@kbAb}@gcCtZarBb_@uZnmAyI`sDsL`sBcp@rw@}JprAkaAbmBecAnl@{{A~bDmqLjDghKdb@ij@|i@O`I}e@QggHhNmbA|a@yf@r[}Inv@gQnk@ii@nn@ea@njDwVpuHgaBluC_{@rrDaeAdmAci@iCglAzUmwAns@ykAt@s{@lJsbB`j@mo@f}@gyCnY}rAzHc|Abu@qvBj`Au~AbVwlBqGmgBaBei@u`@wFql@{h@ySdB_p@wq@ucCk{Bk{Aw`CmaCoaAivCcbAiEaoAhDmhB{wB}wBalAul@_~@a`@ax@ikAq\\sqAb]gwBrzCi`Ij{EwbNmh@a|DUyd@fd@kVn^ae@f|@mlAbd@~Ifr@cKjEcsAaMei@}x@qt@cdAigB_d@uK{kAhEcy@uj@dMmk@pqDqiFbrGwvIxkAubB``@yg@r~@yIhcA__@hwBmgA|qBsbArh@}PjK{{@wBaYff@y`Add@ga@hOgt@v{B{wBt`A{`Als@xAnw@y@zW}Unw@wmB~w@}wCds@sU`w@ed@di@c`A~_Bq^fnC}wBry@srBh|AcuAvpBmnAnPsTvfBvT`lAwh@r^qw@v{BuvEp_@ai@~tBeu@t{Cm~BjKqUEecCfXwkCz`Ck|@bnCeR~wBcbAfe@vBrjAocAboBg~Bt~C{dElq@czAtUcQ`VoNjLgJpz@dvAbc@du@xVtb@xXbs@jX`p@n}@~qAeMraAoNj{Dr@`kAtv@x_A`i@`t@", waypoints: "}dgeFxzeyUfq|Ea|aN", bounds: "{\"south\":36.5906694,\"west\":-119.63836669921875,\"north\":37.72510788462094,\"east\":-117.16588460000003}", city: "undefined, CA"})
r10 = Route.create!({name: "Oceanside", description: "", creator_id: thor.id, distance: 25.99, polyline: "ewqeFjiwjVRDLABPBZDZl@l@XB`@KfB{@TWjAwAnAmAj@{@n@m@lAm@xB]lF]~CFpBBxBIxEc@bEShGg@lG{@tG[hGPpDGvTuApmBkMvi@kDfGBvFv@xCRzAIrDo@jEi@dEm@hHk@bCy@lAy@nAiApA{BhCoFr@m@v@YfC]|Ac@lB_AtE}DnDmCvCkA`BO`EKpBEpAMnAa@rEyCzD{BpBe@nNc@~LStB@vHXjG\\lCGxCu@lHkC`Do@hDqAzNeGpC}@~FcApHUbNKdC]pC_AbCoAlB{AnA}@NCX?l@l@kBrBaElDiD~Ah@rCi@sChD_B`EmDjBsB|K{M~AoAtC{AbDq@xAE~KpAlDR|PhBpG^~EMbD_@xEkAvX_J|@]t@u@vB_BdJmB~Am@dAw@fAMbPNf@IjJyDb@@^TtB|HRhAB`BjCDI~Hc@tB[rAC~@VzAjApAfA^rA@xLsAjAAdFZ|B[zEeClBs@dCU`BRbBCxBK|@AbJhAdDb@lFdAfCj@rAd@tAxAj@ZN?tAJzMYxZg@pF_@bAGVA?}JtFUzFQrGQtKW~L_@VF|D_@|CeAf@[j@s@|@}@dAmApG}FrFcFx@i@fAG~Av@nEJ@{Bf@A`A?tBBtDTlKPhALrCt@nDtB~A`B~FfJzD~GvCjG|MdW|C~FnCvDdBvAhClA~Cp@dBJfBE|H{@|A@pBXdA^~Ax@zFvFzHfInNlO`G`GfAXxAHp@IhAc@zAiAzGuF|@Wt@?x@NdAv@fDtDv@`@bALdAQj@c@`DuCl@[hAEh@Lh@\\x@xAlBhOIf@?b@FtBaBfLd@lOR|DNt@`AfBl@`@n@Nn@B|BO`DCxDRb@HXRpAlBfBz@`Bf@pB`AvBh@|@EjBc@|BE|CHjATpAh@~DtCj@RbAD`AUl@_@|@uAt@gAzAmAlC}Ah@OhAHvB`@ROBY?KTC`@KvAi@t@m@`HsFfD}A|NsEdAQbA?v@FhA`@lDdCn@XfADzA[jAe@jBg@pAF~@f@|BtDbAx@bARlAM~@e@`CgD`Ay@pAm@pDg@|UcCdHm@rDBtDj@pBl@|Av@rJ|FpFdDbHdEvAj@zD|@v]vGdFf@vEBfE[dDo@zFuBhC{ApEwDfPePlNeNnEmEfG{GnDmF`CmExb@saA|A_DbDkF`M_RfJuNlGqJfE}FdD_GjB_EbBsElGaRtGcUlA}ElMmd@vNig@tFkSbAyC~AmF|BgF`C}CtBkBvCiBbRgLnOgJlAaAhBkA`PyJhEgCfBwAv@w@`EuEjPcQtEuEdEoE|EeFnBwB", waypoints: "gxqeFlkwjVl_PykB`aa@b]lqGwmK", bounds: "{\"south\":37.4739691,\"west\":-122.51335144042969,\"north\":37.779398571318765,\"east\":-122.43696299999999}", city: "San Francisco, CA"})



w1 = Workout.create!({name: "Saving Overworked Students", user_id: cap.id, date: "2017-11-08", description: "Most were compliant but a few showed weary resistance, which was neutralized", route_id: r1.id, hours: 0, distance: 6.54, mins: 16, secs: 23})
w2 = Workout.create!({name: "Cross Country Easy", user_id: cap.id, date: "2017-11-15", description: "", route_id: r2.id, hours: 145, distance: 2913.7, mins: 23, secs: 48})
w3 = Workout.create!({name: "TOP SECRET", user_id: cap.id, date: "2017-12-01", description: "[CLASSIFIED]", route_id: r3.id, hours: 18, distance: 532.92, mins: 23, secs: 12})
w4 = Workout.create!({name: "Warmup", user_id: cap.id, date: "2017-11-19", description: "Crushed a gopher on mile 4 but otherwise nothing unusual", route_id: r4.id, hours: 0, distance: 6.64, mins: 22, secs: 13})
w5 = Workout.create!({name: "Dim Sum between missions", user_id: cap.id, date: "2017-12-01", description: "Had a stomach ache. Not sure if due to Red Skull poisoning my delicious food or just food coma...", route_id: r5.id, hours: 0, distance: 6.21, mins: 16, secs: 23})
w6 = Workout.create!({name: "Social Hour with villains", user_id: cap.id, date: "2017-12-01", description: "We wined and dined inside the prison. Had a ball. Must do again.", route_id: r6.id, hours: 6, distance: 33.83, mins: 48, secs: 23})
w7 = Workout.create!({name: "Stroll through Central Park", user_id: sm.id, date: "2017-12-01", description: "", route_id: r7.id, hours: 0, distance: 8.9, mins: 57, secs: 22})
w8 = Workout.create!({name: "Yellowstone Loop", user_id: im.id, date: "2017-11-22", description: "You might say I .... flew through it", route_id: r8.id, hours: 0, distance: 115.59, mins: 18, secs: 23})
w9 = Workout.create!({name: "No Bother Hulk", user_id: hulk.id, date: "2017-10-10", description: "RAWR!!!!", route_id: r9.id, hours: 1, distance: 232.25, mins: 35, secs: 2})
w10 = Workout.create!({name: "Sunday stroll", user_id: thor.id, date: "2017-11-19", description: "I came across some interesting humans who wanted to take a photograph with me. Curious the fascination of humans with 2-dimensional images.", route_id: r10.id, hours: 2, distance: 25.99, mins: 34, secs: 12})



Comment.create!({body: "Wait, who was there?? Anyone I know?", commenter_id: sm.id, workout_id: w6.id})
Comment.create!({body: "Trust me, I know how terrible conditions can be for poor programming students", commenter_id: sm.id, workout_id: w1.id})
Comment.create!({body: "I'm fairly certain I put Ultron in there last week, but has he hacked his way out yet? Any eligible bachelorettes? (FYI I'm asking for a friend)", commenter_id: im.id, workout_id: w6.id})
Comment.create!({body: "That's impressive, but I did it in only 2.5 hours with my new repulsor jets", commenter_id: im.id, workout_id: w2.id})
Comment.create!({body: "HULK....SMASH!", commenter_id: hulk.id, workout_id: w6.id})
Comment.create!({body: "HULK...SMASH!!", commenter_id: hulk.id, workout_id: w1.id})
Comment.create!({body: "HULK....SMASHH!!", commenter_id: hulk.id, workout_id: w4.id})
Comment.create!({body: "Bruce, thou shall not smash these villains, no matter how unjust their actions may be.", commenter_id: thor.id, workout_id: w6.id})
Comment.create!({body: "I'm pretty sure I know which mission you're referring to here. (It was Thanos, right?? right?????)", commenter_id: thor.id, workout_id: w3.id})
Comment.create!({body: "My mighty Myolnir got me there in 2.2, plus I stopped to help some bystanders several times as well", commenter_id: thor.id, workout_id: w2.id})
Comment.create!({body: "Oh Hulk... come to a Himalayan mountain and meditate with me sometime", commenter_id: drs.id, workout_id: w4.id})
Comment.create!({body: "I hear the BBQ Pork buns and chicken feet are especially good. I'll have to stop by again next time the universe stops being threatened", commenter_id: drs.id, workout_id: w5.id})
Comment.create!({body: "All mutants and humankind should peacefully coexist. I wholeheartedly endorse these endeavors", commenter_id: prof.id, workout_id: w6.id})
Comment.create!({body: "Steve, please see me immediately to discuss the rules regarding mission etiquette", commenter_id: prof.id, workout_id: w3.id})
